# Generated by Django 5.0.6 on 2024-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='detail_ext_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
