# Generated by Django 5.0.6 on 2024-05-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0002_author_detail_ext_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='detail_ext_link',
            new_name='website',
        ),
    ]
